### ISSUE TITLE
Add documentation in README

### ISSUE THREAD

**Issue by adamilyas** [hajimss/flask-and-mongo#1]
Documentation should include
- how should i, another user, clone your repo and run the project locally
- what end points and methods are available ? eg. GET /friends
- what is the architecture ? e.g. HTML/css/ frontend - python flask backend - mongo db
- deployment
etc..

**Comment by hajimss** [comment]
Thank you for the input, Adam. I'll be looking to populate the Readme with the relevant information. I appreciate the points given. It will certainly help me think of the content and the writing process will be a much smoother process.

**Comment by hajimss** [comment]
Populated README with necessary information. Thanks again for the points.

**Comment by adamilyas** [comment]
Ok
