### ISSUE TITLE
Please move credentials to environment variables 

### ISSUE THREAD

**Issue by adamilyas** [hajimss/flask-and-mongo#2]
https://github.com/hajimss/flask-and-mongo/blob/3e83b8f8b2a06fa46702373d4bba8e573d8f2e45/server.py#L25

Please do NOT hardcode credentials. Move to environ variables, since you are using heroku, you should configure it under config vars: https://devcenter.heroku.com/articles/config-vars

**Comment by hajimss** [comment]
Thanks for the save. I have already edited the variable to MONGO_URL under secrets and config vars for github and heroku respectively. Code has been pushed to both repo.

**Comment by adamilyas** [comment]
https://github.com/hajimss/flask-and-mongo/blob/d2fb314d4db9e1e954784de20f07b489157f9d76/server.py#L25

Where is MONGO_URL defined at?

**Comment by adamilyas** [comment]
https://github.com/hajimss/flask-and-mongo/blob/6c804a9c9fb64fb2a54ab16a412461d03edee251/server.py#L19

This issue can be closed.
